### ISSUE TITLE
iterative correction bug in inspectro

### ISSUE THREAD

**Issue by agalitsyna** [open2c/inspectro#2]
After installing inspectro from environment file the rule `eigdecomp` has failed with this error: 
![image](https://user-images.githubusercontent.com/8100372/204598904-abd71627-0a50-42fa-970c-8908e9ff179b.png)

Upgrading cooltools (installed locally from GitHub) and changing the import in eigendecomposition script (`from cooltools.api.eigdecomp import _filter_heatmap, _fake_cis`) fixes it.

**Comment by nvictus** [comment]
Fixed in f9c1733363fa1ffc0b81b04b85a6a76a822281fc
