### ISSUE TITLE
Cluster numbers showed in heatmap and scatter plot don't match ?

### ISSUE THREAD

**Issue by liu-zhiyang** [open2c/inspectro#6]
Hi,
I am trying to do egien decompsition with inspectro and I have got the results. But when I check the figures, I find the cluster number showed in heatmap and scatter plot don't match. For example, in `E1-E128.kmeans_sm7.heatmap` file, there are 7 clusters, but in `E1-E128.kmeans_sm7.scatters` file, there are 8 clusters named 0 to 7.
<img width="1764" alt="image" src="https://github.com/open2c/inspectro/assets/43285689/87a913d7-08ef-4bb4-a925-0ff84fd3d3fe">
<img width="346" alt="image" src="https://github.com/open2c/inspectro/assets/43285689/c764b478-9ecf-4d68-a728-48d993fd5d9f">

I wonder if it's normal or some one is omitted in heatmap?
Thank you very much!

**Comment by nvictus** [comment]
Cluster 7 corresponds to genomic bins that were filtered out from analysis, so it is omitted in the visualization.
